* tomsinsight-free
** [[http://bbs.kafan.cn/thread-1767759-1-1.html][中国互联网黑市门槛(一) 信封号产业链]]
2013年中旬，美国一家互联网公司进入中国，在产品落地和市场竞争分析时找到TOMsInsight团队做顾问。这家公司的优势是技术和产品设计，但国内有两家无节操的山寨模仿者。美MIT毕业的年轻帅哥CEO对之极其不屑，而我们团队的首席分析师非常明确直接的告诉他：“你会输给国内的山寨公司，因为对方在APP营销的时候已经开始使用信封号。而你不会用也不能用。”当这位CEO得知什么是信封号营销时候，非常诧异地睁大的眼睛，做出一个C罗进球庆祝似夸张的表情。几个月后，美国公司退出了中国市场。而那个夸张的表情一直留在我脑海中挥之不去就像魔咒一样。



在中国，大多数行业都有一定的门槛，有人喜欢称之为：“黑市门槛”。意思是很多交易是见不得光的，属于潜规则范畴或者是不为人知的行业秘密，有一定的非法性，只能在黑市交易。这种信息只流传在最信任的人脉圈子里。让行业外面的人或者是新人一头雾水，或总是被老鸟们称为：不上道。

而中国的互联网行业，也是如此。

了解“黑市门槛”，最好从黑市入手。而读懂了黑市，看明白了黑市的交易，弄清楚了交易背后隐藏的利益链条和规则、以及见不得光的秘密，也就读懂了所谓的“黑市门槛”。

TOMsInsight接下来会推出一系列的互联网黑市的分析报告，每期登场一个主角。

今天的互联网黑市主角是：信封号产业链。
*** 什么是信封号？

信封号，就是被盗的QQ号。信封号产业链，就是QQ号盗取、销赃、并利用获利的产业链。被盗的QQ在黑市上称之为“信封号”。在中国，QQ作为人人必备的IM软件，有8亿以上的用户数，最大2亿以上的同时在线量，对周边生态环境有着不可估量的价值。


取信：一组QQ用户名和密码称为一个“信”，一个信封就是一万个（或者一千个）被盗的QQ号和密码。通过各种手段盗取QQ号码和密码，以万为单位保存成信息文本。拿到这些信息被称为：“取信”。

洗信：通过一些工具，将信里面有价值的信息（QQ币、有价值的游戏虚拟装备、QQ靓号等）筛选出来的过程称为“洗信”。有专门的“洗信人”或者是“洗信工作室”来完成。

洗信过程：盗取后就没有经过任何清洗的信被称为一手信，一手信的洗信主要就是三步：第一步洗Q币，把信封里面Q币都转移出去，然后在黑市上出售；第二部是游戏虚拟装备，腾讯公司的主要收入就是来自游戏，而被盗取的QQ号中蕴藏的游戏虚拟财富必定不菲，所以洗信人接下来会把游戏装备、游戏积分、游戏账号以及游戏币等凡是能兑换成钱的游戏财物转走，存入固定账号。第三步就是QQ账号，挑QQ靓号（五位数、六位数、或七位数的短号，或者一些含有吉祥数字的号码）来观察是不是有密码保护或者死保（申请了密码保护资料，但是原主人忘记或者丢失了密码保护资料）。

二手信：一手信经过洗信后，称为二手信。二手信一般以更小的单位出售，在二手信的黑市上，一个信封一般只是一千个号。二手信经过洗信人的封装，分成不同的种类，不同的种类有不同的用处，下面是几种比较常见的二手信：

群发信：用来给被盗号的每一个好友发消息，一般发的消息都是特定的广告，例如各种网页游戏，特定的论坛等等，而现在很多APP的广告也开始使用群发信。

广告信：在QQ空间内植入广告，由于大多数人都开通了QQ空间，而一个人的QQ空间又会影响被转载到多人，所以效果明显，而且成本低廉，深受一些网络推广者喜爱。在QQ空间植入广告的信封由于腾讯安全策略，必须是能提取cookies的信封，就是无需验证码直接登录的信封，所以在黑市上也叫cookies信。


（本文开始提到美国公司在国内失败的例子，就是国内的模仿者在APP推广阶段使用了广告信和群发信。）

忽悠信：黑市上的买家登陆被盗的QQ号给好友发一些诈骗消息，一般都是急需钱或者出事了之类的骗术。在忽悠信中还有特定的分类： 海外留学忽悠信、女生忽悠信、18-23岁忽悠信，微信忽悠信等。可以类推这些可耻的骗子的手段。

在这个封装过程中，信封的封装者和黑市上的卖家，充分的发挥了创新能力，出品了各种各样的信封：地区信、八位信、过夜信、90后信、蓝钻信、游戏信、等等，几十上百种，分别在黑市上卖给不同目的买家。

点击查看原始大小

老信： 最后被榨净的QQ号还会卖给黑客用来编写密码词典，或者邮件群发者群发广告。被盗的QQ号码是黑客用来计算用户密码习惯最好的素材。他们进行编译、分析、比对后，从而对网银或者支付宝之类支付工具进行破解。而邮件群发者不在乎用户是否找回密码，只是根据特定的信息，来发放广告。老信还有其他特定用处。

在这个产业链上，每个阶段的工作一般都由不同的“洗信工作室”专攻，而且会非常“守信用”：“洗币”、“洗游戏装备”、“洗靓号”、“做忽悠”、“做广告”等每个部分之间绝不相互侵犯利益。

点击查看原始大小

最夸张的是，由于一般都是在晚上12点开箱子（下文介绍，开箱子只指新鲜的信封被放到市场上），而到了第二天天亮，被盗号的用户都会发现自己的QQ号被盗，从而修改密码或者采取安全保护，让信封中大量的号失效，所以整个销赃的过程都集中在晚上12点早上7点之间。所以看似复杂的过程，在互联网黑市上，只用了7个小时就彻底完成了从头到尾的完整的流水线。每一个信就像一头牛，从剥皮，拆骨，切肉 … … 到了早上7点，只剩一滩血污。

信封号的生产过程

每天，中国互联网黑市上的信封号出售的数量都大概在1000万个左右，TOMsInsight通过一些非常规手段监控2014年5月份一个月内黑市的出售二手信封总数量可以见下图，我们能监控到的样本只占少数所以通过一些算法预估和去重，数据并不非常精确：

点击查看原始大小

而这么多的信封，是如何生产出来的呢？

在信封的生产过程中，最核心的也是整个产业的“老大”一般在黑市上称为“总代{过}{滤}理”。总代{过}{滤}理首先向木马程序编写者购买或者定制专门的盗号木马（做马），然后委托一些流量商，将木马挂在网页上。用户只要点击该网页，或者是下载了网页上的资源，其计算机就会被植入木马；木马将截取到的QQ号码和密码发往指定的服务器，总代{过}{滤}理每天晚上会在11点左右把收到的号码和密码信息整理（开箱子），分给下面的二级代{过}{滤}理（二级带来再分给三级，根据信封的数量），开始在黑市上销赃。

这个产业链中。流量商扮演了极其重要的作用，对于总代{过}{滤}理来说，拥有一款效果稳定的木马和下级“二级代{过}{滤}理”以及“洗信人”只是第一步，他们更需要将木马植入到用户的电脑中，才能真正获得利益。因此掌握着大量网站资源的人被总代{过}{滤}理们格外珍视，这些人在行业内被称为“流量商”，即“挂马”人。流量商或者自己是网站的站长，或者与很多网站站长熟识，他们将病毒木马挂在点击率较高的网页上，当用户点击到那些弹出窗口时，木马病毒就“种”到了用户的计算机上。

在目前行业内，流量商根据IP流量对网站进行付费，1万IP大约需要100元到200元人民币，而流量商向总代{过}{滤}理收费则是按信收费，一万个信1000元到1500元不等。而一个质量比较好的站，3万左右的流量就可以拿到一万个信。代{过}{滤}理人虽然是整个产业链的核心和“老大”，却处处被流量商制约。流量商也在黑市上被称为“做箱子的”，行业内，很多总代{过}{滤}理为了讨好流量商，还会对采取分成的合作模式，有的强势的流量商甚至可以拿到比总代{过}{滤}理更高的分成。（渠道为王真是在黑市也成立啊）

点击查看原始大小

有人的地方就有江湖，信封号的江湖，精彩纷呈，比之香港黑社会电影是有过之而无不及，更多的斗智斗勇，更多的创新颠覆，让这个不合法的产业链越来越精彩。

在这个信封号产业中，每一个细节都有各种复杂模式我们就不一一叙述，有兴趣的读者可以使用我们微信号的服务进行交流。在此我们更多是希望给大家展示出这个产业链的面貌。

对我们的启示

我们团队分析这些，绝不是希望大家成为这个产业链上的一环，更不是希望大家购买各种信成为黑市消费者。相反，整个信封号产业链都是绝对违法的！我们只是希望通过这样的分析，给大家揭示中国互联网的完整的面貌。

当绝大多数人的眼光都盯着BAT等互联网巨头。各种媒体、专家、互联网分析师、观察家们都在讨论着微信的战略、小米的互联网思维、O2O、特斯拉如何重塑行业、等等的时候。岂不知这些都是互联网行业这座冰山浮到外面的风景，而那冰山的巨大的水底世界，却又不为人知。当你熟读了各个互联网巨头的战略，看尽了互联网思维，想出一个颠覆性产品、然后进入到这个行业的时候，其实等待着你的其实就是这些。

在探索出真相之前，问题没有那么简单。
** [[http://chuansong.me/n/626559][中国互联网黑市门槛(二) 安卓地下渠道]]
垄断是很可怕的事情，不仅仅是商业资源，更是一种潜移默化的思维方式。当在一个行业内，主流观点都被垄断的声音所引导，这个行业的创新也就会被定向或遏制。很多大公司都会有EVANGELISM这样的一种职位，翻译过来就是“福音传道者”，主要的工作职责也就是引导行业内的声音、销售观念或者趋势。
这种定向和遏制的一大特点，就是把所有行业内的资源都集中到“主渠道”中来，围绕主渠道打造生态系统。主渠道的优势不仅仅资源上，更多的是行业方向引导、各种概念引领、话语权、精神优势等等，于是慢慢出现渠道为王的局面。
我们可以想象出国内各行各业都最常见的一种场景：产品商和渠道商一起吃饭，主渠道的人坐在主位，坦然的接受各种朝拜，提携关系不错的上下游产业链节点。二渠道也总是和人悄悄约好换个场子再聊。也有一些人，自始至终没能和主渠和二渠说上一句话，甚至连点上个烟的机会都没有。如果是在传统行业，估计他会继续经营关系，找门路，开辟新的合作。

但是在创业者普遍把自由和尊严看的比生存还重的互联网行业里，他们在咬牙切齿中，决定卧薪尝胆跨向一条剑走偏锋的道路。
TOMsInsight继续我们的互联网黑市的分析报告系列，今天的主角是：安卓地下渠道。
*** 安卓的主分发渠道
我们从用户需求角度出发，安卓的分发渠道大概可以分成：手机预装，按需安装，诱导安装，静默安装，这四种情况。而下面我们大概概括一下这几种分类方法下的分发手段。

*** 手机预装：
手机预装就是在用户购买手机之前的预装渠道。预装有相对正规的渠道，比如和手机制造厂商合作，或者和定制运营商合作。不过更多是存在刷机利益链中。

刷机利益链先从窜货说，外国卖的手机流通到国内来，叫做窜货，我们一般称之为水货。一个机型的手机水货和行货一般会有很大区别，特别是语言。走私商通过一些技术手段，把原来的外文版刷机变成中文版。由于水货手机的发展越来越快，分工也越来越细，渐渐形成了一批专门做刷机的利益体。国内的app公司为了使自己的应用覆盖跟广泛的人群，通常会和一些刷机商合作。

不仅仅是水货，由于利益驱使，行货的手机也会被再次安装应用。在销售渠道的各个环节：仓储过程，手机运输过程中，甚至在各个手机卖场都会被安装新的应用。各个节点都会被充分利用，抢占这一入口。这也是一个博弈的过程，之前被安装上的应用会被下一个环节恶意刷掉。

有朋友可能问，新手机怎么会被打开刷机呢?我如果告诉你有专用恒温吹风机吹开密封条，你会相信么?我们的一个小伙伴从著名的家电销售企业买过一个手机，技术手段读取后台日志分析，发现在购买前一个月内，9次被刷入新的应用。换句话说，这“新”手机至少被打开了9次，可怜的密封条。

*** 按需安装：
按需安装是安卓分发的最主要的渠道，也是最正常的方式：手机的使用者按照自己的需求选择app下载使用。由于安卓系统的开放性，程序的任何存放都可以激活分发，所以按需安装也演变成各种各样的细分。

目前来说，主要的按需安装分发渠道有：国内各大第三方市场、Google官方市场、搜索引擎、手机管理工具推荐、巨头应用推荐、广告联盟、移动类广告(广告贴、插屏、消息、积分墙等)，PC类广告(广告平台，大流量CPM、精准CPC等)、SNS平台推广、内容营销推广、各种开发平台应用、新兴的wifi渠道、还有传统互联网分发手段等等。

另外一个正在快速崛起的渠道是线下渠道，由于主要针对三四线城市或者外来务工人员集中区域，线下渠道针对特定的应用，也在快速的形成小产业链。

按需安装以用户的需求为出发点，也许很多渠道都会有一定的诱导成分( 积分墙 )，但是也都没有到夸张或者离谱的地步。

作为安卓分发的主渠道，应用市场也是各大巨头的战场，而目前也逐渐进入到寡头垄断的局面，以360、百度系、应用宝、小米几家为代表的寡头甚至占据了6成以上的应用市场分发流量。主渠道的特点非常鲜明，流量集中，虽然一些长尾流量也转移到搜索引擎中，但是供给跟不上app的需求，也推升了流量价格越来越高。

我们跟踪不同分类的50种应用在安卓主渠道的有效激活价格和有效用户获取价格，在过去五年内的变化如下图：
*** 诱导安装：
诱导安装是利用一些技术或者宣传手段，让用户对应用的质量和内容产生不合理的预期，而诱导下载使用。例如刷榜，是让用户感觉应用质量很好能排名前几;例如美女类诱导，让用户对内容充满幻想。诱导安装是一个非常灰色的地带，不能说完全不合规，但是也充斥着黑市手段。

最早曝光的是刷榜，刷榜在行业内是常态，但是在2010年被媒体曝光后变得出了名：当时著名的曝光点是一家应用的作弊器忘记关，结果刷的流量超过了雅虎。刷榜就是用自己下载应用商店里自己应用的方式，获得排名，从而获得真正的用户。这个和当年SP的自消费业务类似，后来的刷评论也是一样的道理。

接下来是山寨应用，由于安卓应用使用java开发，不是原生机器码所以非常容易反编译。流水线一样，批量盗版上千个应用，加入广告，积少成多，赚取流量，出售流量，形成了一股不小的分发渠道。

换壳美女应用也很常见，大家可能会在各大应用市场上看到各种大同小异的美女图片应用，由于人性所致，美女图片类应用被下载次数较多。于是渠道开发一个应用，提交上线后，把自家应用换个皮，改名，再提交一次，不停的换皮，改名，于是，每一次短暂的曝光机会都能带来一些流量，成千上万聚集，也会有收获。

另外还有一些成人论坛，或者是传统网站的一些大流量站群、垃圾站站群、SEO站群等等所有的细微流量聚集的地方，用极其诱惑的广告语或广告图片，让用户产生预期，从手机流量导入形成分发渠道。

甚至是利用信封号(TOMsinsight有之前有报告单独分析信封号产业，请到添加我们微信号：TOMsInsight，到“历史报告”去查阅)进行强制QQ空间传播和欺骗好友。

诱导安装在目前的安卓分发渠道中占据了非常大的一环，虽看起来并不如前两种规模，但由于比较低调隐秘，没有聚集，再加上分发的应用数没有相对应的数据宣传，不过总量不可小觑。

*** 静默安装：

静默安装就是指软件在安装时无需用户的干预，直接会按默认设置进行安装。

对已经root过的安卓手机来说，应用是可以获得静默安装的权限的。如果你不幸下载了有静默功能的应用后，在你半夜睡觉的时候，你的手机突然下载了很多应用，然后自动打开，自动联网，甚至还可以然后自动卸载，一点痕迹都没有。

或者水平更高一些的，把一些app做成木马病毒，不仅仅可以自动静默安装下载app，还可以有自动去传播，获得更多的被控制的手机。比如之前被曝光的一些手电筒应用。

被静默程序控制的手机一般在黑市上称为：野鸡。而被木马程序完全控制的，被称为：肉鸡。

不管是野鸡还是肉鸡，最早，大家都是靠着SP暗扣赚钱的(通过控制短信或者流量接口，在用户不知情的情况下发送短信或者访问网站，和SP分成)，但是慢慢的通过SP赚钱的越来越少了。这是怎么回事呢?难道野鸡和肉鸡越来越少?

不对。肉鸡越来越多，甚至在国内已经形成了几个非常大的僵尸网络(一群被控制的肉鸡组成的网络)，但是都不做暗扣了，因为大家找到了更好的商业模式。

我们接下来分析。

*** 地下分发渠道

我们看完了目前几乎所有的分发渠道后，回过头来继续分析。哪些是所谓的地下分发渠道呢?其实，地下分发渠道，只指能分发非法app应用的渠道，只要你能把非法的app分发出去，这个渠道就是地下分发。

那哪些应用是非法的app应用呢?

安卓应用的开放性决定app有两种类型，一种是直接变现，一种是再分发。第一种大家很容易理解了，比如在手机上装一个游戏，玩游戏买道具直接变现。还有另外一种，比如你安装了一个应用，通过这个应用你还能获取更多的应用(例如应用市场)，这就属于再分发。再分发应用相当于是渠道布局。

非法应用也有两类，针对直接变现的“暗扣黄赌”应用，和针对于再分发的木马病毒类应用，后者也是静默渠道的形成过程。

所以分发“暗扣黄赌”和“木马病毒”类应用的渠道，我们就定义成地下分发。

我们可以从下面图中看到2010年Q4的地下分发渠道在刚才说的四种渠道中的构成。


几乎全部的静默安装渠道和一部分诱导安装都可以算是地下分发渠道，由于2010年Q4时监管问题，手机预装和按需安装也会有一部分。


但是再对比一下2014年Q2的构成，忽然发现，主力军静默安全渠道，忽然间都不分发非法应用了!那他们都在干什么呢?

“风投和海龟的钱那是最好骗! ”

从2012年开始，由于资本开始追捧移动互联网行业，再加上移动应用分发渠道的集中，供给跟不上app的需求，让移动分发成本飞速增加。

到了2012年中旬，国内主流的安卓cpc激活渠道价格已经到了2-3元每个。而这个时候，静默渠道开始放弃了暴利的“暗扣黄赌”进入到分发渠道。由于静默渠道有其独到的优势(可以控制手机下载、打开、甚至使用)所以激活率非常高。

C哥在静默渠道行业沉寂已久，他给TOMsInsight的分析师算过一次帐，在2012年的时候，“暗扣黄赌”类应用里面最赚钱的暗扣，平均每一个“肉鸡”月aurp值大概是在30元左右，除去下游的SP分成和环节成本，他们可以做到10元每月每个“肉鸡”。但是如果做静默激活，非常轻松可以一个月超过50元每个“肉鸡”。

比“暗扣黄赌”还高5倍的收入，谁还做非法生意呢?

应用app公司慢慢发现大量的用户虽然激活，但是使用率变现率都为零或者很低，从各个渠道过来的用户大多无效，所以导致了有效用户的成本越来越高。

而到了2013年，移动互联网竞争愈发火热，再加上91被百度的高估值收购，资本市场的再次追捧，有效用户成本的获取价格再次增加。而这个时候，手里面掌握大量“肉鸡”组成的僵尸网络的C哥，开始进入一个新的领域，给app应用做数据。这是什么意思呢?

控制僵尸网络，不仅仅用静默的方式安装一个app应用，接下来还控制着这台手机，打开应用、使用、关闭、再使用、甚至消费消费。完全模拟一个真实的用户的行为。这一切都在这个手机的主人完全不知情的情况下(一般都是半夜)发生，而到了早晨，自动卸载掉app，不留痕迹，晚上继续下载，继续模拟。

对于app应用制作商来说，后台数据非常漂亮，用户看上去非常真实，甚至还有一定的消费数据。于是C哥的渠道越来越受业内欢迎，当然这样的“真实”用户的成本也越来越高，在一些细分甚至达到几十块每个。

“大多数app应用公司的老板，都不知道自己的数据是假的。还都以为自己的产品很牛逼，投资他们的风投，还以为自己很有眼光，接手的B轮，C轮，继续炒作，还以为自己捡到了宝贝。其实，风投和海龟创业者的的钱，那是最好骗了，骗到他们几乎都要快上市了都没人能发现，而所有的投资，一大半都被我们赚走!”C哥完全没顾忌到对面TOMsInsight的几名海龟背景的分析师，非常嚣张的喊道。

而“野鸡做激活，肉鸡做数据”已经成为这个地下分发渠道的核心秘密。

从最新的趋势看，有一些极其有前瞻性的僵尸网络商，连做数据这些的业务都不做了，他们沉浮下来，专心去分析用户行为，对app应用市场进行分析。这也是C哥的方向。

“appannie公司做的事情，我们完全可以好上100倍!但是我们现在不急着卖数据，等着他们去炒作大数据的概念吧，价格高了再玩。”C哥对现在自己的产业的变现和未来，都极其充满了信心。

还有一些僵尸网络商，不做数据，专心去盗取用户的手机支付等工具用户名密码，这是一些小众和完全违法的产业链，随着国家的严打和用户的警惕心，已经在凋零了。而C哥为代表的新兴地下渠道在兴起。

总之，主渠道的垄断，让地下分发渠道变得极其活跃和水深，利用僵尸网络，刷出假数据，助长了整个行业的虚假繁荣。而资本的追捧和利益导向，击鼓传花般的让繁荣继续传递。我们不知道在商业上谁是最终受害者，但是可以肯定的是，用户是，整个行业也是。

*** 给我们的启示

从人类的发展开始，文明总是最先繁荣在各大流域。历史上，黄河及沿岸流域给人类文明带来了巨大的影响，是中华民族最主要的发源地，我们称其为“母亲河”。后来经济发展的集中地，黄河流域、长江流域、珠江流域，都是在围绕渠道产生，渠道，是文明产生的根基。

中文的博大精深，在目前的商业社会，也给与“渠道”已新的含义。但是渠道本身的价值，也在商业竞争和变革中产生了变化。特别是互联网这样一个新兴的，创新的，代表着未来和趋势的行业。也许我们应该时不时的思考，创新的真正价值和真正的意义。

正如那句话：给岁月以文明，而不是给文明以岁月。

** [[http://www.ityuedu.com/article/6148291056/][中国互联网黑市门槛(三) 百度竞价单页]]
百度一直饱受争议，但是很少有人深入下去了解百度与他的中小广告主客户们构建的生态环境 。 大家总是拿百度和Google相比，看的是如果击败Google，如何和360PK等等，但是这些都是表象。 如果不去深入的看到这些公司的盈利和生态环境，仅仅在表面大谈特谈战略和未来又有什么意思呢？
下图我们选取了互联网广告的热门的10个行业，通过技术手段对比了特定时间段内Baidu和Google的CPC价格（CPC是指Cost Per Click，广告投放后按照每一次点击付费，是Baidu和Google的主要广告售卖方式）
而这又是怎么回事呢？ 难道中国的经济水平远远超过了美帝国主义？ 还是百度和Google就是完全不同的公司呢？ 为什么有些行业差别这么大？
TOMsInsight继续我们的互联网黑市的分析报告系列，今天的主角是：百度竞价单页。
*** 从电视购物说起
我们在说百度竞价单页之前，先花点时间回顾一下当年的电视购物。 在90年代后期，电视购物和声讯电话就好比是就是现在的电商和手游。
电视购物在1992年进入中国，当时很高大上，广告产品都是市面上少见的，再配上非常夸张的广告效果，加上没有渠道成本，非常暴利。 1996年，以舒亦康、帝威斯等为代表的第一批电视购物机构兴起。 此后，各类卫视、地方电视台电视购物风起云涌。 1998年进入发展高潮，电视购物遍及28个省市，市场规模达到了30亿元人民币左右，销售额占当年社会消费品零售总额的0.5%，2002年到1.2%左右。 （参考数据：目前火热的电商大概在8%）
由于当时电视购物不受广告法的监控，变得极度的夸张。 专注在如果抓住消费者心理：主持人语速极快极有煽动性，不给消费者的大脑留下思考空间，有计时器，加上一些“限量”等等，很容易勾起购买冲动和不理智心理。
而消费人群主要是集中在三四线城市，年龄偏大，接受信息的渠道有限，信息不对等，对电视比较盲目的信任。 所以，电视购物的本质是利用消费者对电视频道的信任，利用频道的剩余资源加上特殊的目标人群产生销售的行为。
2006年8月1日国家广电总局、国家工商总局颁发了对药品、医疗器械、丰胸、减肥、增高产品等五类商品（简称黑五类，下文中也称之为黑五类）不得在电视购物节目上播放的法规条令，可以说是电视购物在中国落地以来，第一次被重拳出击，电视购物遭遇严重的信誉危机。
也是那一天开始，“黑五类”离开了电视频道，找到了新的广告平台：百度。
*** “黑五类”的胜利大迁移
2006年的百度公司，上市没多久，利润还很低，只是占领了一部分中国搜索引擎的份额。 采用了“竞价排名”的商业模式。 用一个更合适的名称， 这种商业模式叫“关键词广告”：广告商把广告按照关键词进行投放， 搜索引擎在用户搜索相应关键词的时候， 保证广告内容能有效达到目标客户。
当时的情况下，对中国的中小企业主来说，“关键词广告”模式很陌生，不能找到合适方式：如果是品牌广告，通过关键词给自己的产品打品牌，CPC的模式过于昂贵。 “关键词广告”适合极其精准的客户，而对于这些极其精准的客户，广告商买来这个关键词，投放广告，又如何变现呢？ 对于2006年的中国互联网其实是一个大难题。
但是没关系，“黑五类”来了以后，一切都迎刃而解。
“黑五类”的广告商在电视购物领域积累了大量的对中国三四线城市的终端用户的经验，用现在的话说：就是相当的了解屌丝用户。 利用的是电视频道的流量和信任，当电视购物被禁止以后，急需找一个被信任的平台急需投放广告。
忽然发现一个新大陆：被大家信任（当时网民普遍心理是，披着技术外衣的百度搜索出来的结果都是靠谱的，排名靠前的是最值得信任的），可以随便购买流量，用户还可以精准，再加上网络广告不被任何监管。
哇塞！ 早知道有百度，我们为啥还在做电视购物呢。
于是，2006年年底开始，百度上一页之间，充斥了竞价单页。
*** 什么是百度竞价单页
那到底什么是竞价单页呢？ 就是网站一般只有一个页面，但是内容丰富，和电视购物一个套路，专注在如果抓住消费者心理：页面上充斥着大量的图片、视频，销售话术极其有诱惑煽动性，充斥着大量的不合乎广告法的文案，在补充以什么权威机构、专家、医生等来证明是靠谱的。 几乎就是完全把电视购物的效果照搬成一个网站，而一般都采取电话订购或者网上订购，最关键的是采用货到付款的方式，方便不懂网络支付的客户购买。
如果你还不太明白什么是竞价单页，打开百度，随便搜索：减肥、瘦身、丰胸、增高等相关的关键词，排名靠前的网站打开看一看就是了。
竞价单页再配上专门的网页客服软件（打开网页就弹出客服对话框），就形成了一个比电视购物更优越、更能施展的平台。
有一个数据，2006年到2007年度，百度的新开户数量高达6万多。
“黑五类”的广告商成功完成了战略大转移。
*** 竞价单页的生态圈
有人说， 竞价单页可能是中国互联网水最深的一个行业 。 看上去非常简单的页面，非常明确的盈利模式，由于暴利和容易复制，导致了大量的隐秘的不为人知的圈子的秘密。 这些秘密在黑市上流行，而又不断的进化。 我们可以按照时间顺序把从2006年开始的近8年来的竞价单页的生态变化大概分成下面几个阶段。
**** 明拍：
最早的百度竞价采取的是明拍，也就是当年被人诟病的“竞价排名”，大家出价多少一目了然，出价高的排名在前。 如果广告主准备买“减肥茶”这个词，目前在页面排第5名的出价在20元一个CPC，自己要排名第5，至少要出价21元。 那么他就会估计一下自己的成本，能不能负担的起这个21元：假设30个点击能带来一单，那么一单就需要有630的广告成本，如果没法负担这个价格，那么他就不会参与。
明拍让“黑五类”的暴利程度大大降低，形成恶意竞争，把大量的利润都送给了百度。 而和所有的明拍系统一样，到了一定程度会产生边际效应：只有大的玩家在玩，小玩家根本玩不起了，总的广告主数量有限，所以也让百度的盈利停滞不前。 于是百度在2009年彻底改变了“竞价排名”策略，在2009年12月份推出了“凤巢”系统。
**** 暗拍：
凤巢系统是百度搜索推广系统专业版，于2009年12月1日正式上线，其与竞价排名在关键词出价、排名、计费方式上都有很大的区别，引入了质量度的概念。 综合排名指数（CRI），即出价与质量度的综合算法后，才是排名真正的衡量标准。 这就是说，如果客户有很好的质量度就有可能在出价较低的情况下排名靠前。 这套系统是非常复杂，上线、下线、流程、创意、提词等等模块都有着不断的策略优化。
但是凤巢的本质，是一个暗拍系统。
百度推出了暗拍以后，股价开始了第二次飞跃。 本质是这个生态系统里面的玩家大大增加了，以前看到价格都被吓回去的玩家，都重新进入到这个暗拍系统，大家斗智斗勇，百度从被一些大玩家垄断到了新的“长尾时期”。
最关键的是，百度随时可以修改广告的展现策略来调整游戏规则。
**** 代发平台：
由于暗拍的存在，吸引了大量玩家的进入，有些直接主打一些小众的关键词，或者长尾词，有些专门针对一个地点（凤巢支持特定地区投放），有些专门针对一个时间（凤巢支持一定时间投放），各种竞价单页的玩法层出不穷。
但是新问题来了，这些小玩家，很少能像那些大玩家一样，有自己的产品设计、包装、制造、客服等配套服务，大家更多的只是复制别人的单页、进货、发货，甚至客服的精力都没有。
于是第三个阶段出现了，国内出现了一批代发平台，代发平台什么意思呢？ 这个平台上有所有适合百度竞价单页的产品，主要都是“黑五类”或者是最近几年出现的各种山寨手表、数码等等，只要你加入这个平台，再去百度开一个账户，你只需要集中精力在广告上，有了订单只需要给代发平台，代发平台帮助你发货，回款。
2012年中旬，国内大概有7家左右特别大的百度竞价代发平台。 到这个阶段，这个圈子的产业链开始形成。
**** 盗单：
产业链形成后，百度单页竞价生态圈里面的玩家越来越多，在2012年的左右，仅仅竞价单页类的广告账户就大概有20多万，一年大概给百度贡献了200多个亿的广告费用。
而资源（PV和广告位）也在足部的饱和，暗拍下的价格也在足部升高，已经能和之前明拍的时候相持平。 这个时候生态圈里面开始了一股很奇怪的风潮：盗单。
由于单页主要重视的是图文广告，对安全性没有重视。 甚至都是大量的仿站，订单系统都是由几个简单的网上源程序修改。 再加上代发平台控制着大量的订单，非常容易被攻击。
黑客攻击后，订单再次转卖，由于百度单页的订单都是后付费。 黑客盗用订单后，直接卖给代发平台即可，所以很多黑客都是代发平台雇佣。
这个阶段一片混战，但是除了大玩家，还是代发平台统治了小玩家。
**** DDOS：
生态圈又回到了大玩家的时代（包括代发）。 但是大玩家之间的争斗地盘的生意更加激烈。 为了统治每一类产品的关键词，大玩家之间开始动用了DDOS.
关于DDOS这个中国互联网圈子最常使用的武器，TOMsInsight接下来会有专门的文章分析在此不再赘述。 百度凤巢有个策略是如果网站如法访问会自动下线，所以当一个网站被DDOS的时候，也会自动从广告系统中下线。
一直到现在，很多领域的关键词都是被垄断的，如果你复制一个竞价单页去百度开户，有时候代理都懒的给你开，因为大家都知道你用不了多久就由于被DDOS的无法自理要求退款，还不够麻烦钱。
**** 联盟：
到了2013年，百度最赚钱的关键词广告，全部都被“黑五类”大玩家所统治，当然还有一些新兴的行业（职业教育、美容手术、留学中介等）。 这些行业的大玩家发现，我们整天的在一起打来打去，钱都被百度赚走了，这样不行啊。
由于大玩家就那么一些，大家在几年以后开始坐下来谈一谈，达成一个联盟。 不再勇猛的暗拍，激烈的DDOS.大家私下排名好，都出低价，然后别的小玩家要进入就用黑客手段弄死。
这也极大的影响了百度的利益。
2013年，百度的股价一度到跌破90美元，成为一个低点。
**** 移动时代：
到了2013年下半年，移动流量在百度的搜索的比重越来越大。 很多媒体都在说百度在移动的新时代落伍了，百度没有拿到门票。 但在我们看来，移动时代的到来反而救了百度。
因为在2013年刚刚形成的联盟，被移动时代的一些新玩法打破了，移动上的单页竞价和PC端几乎完全不同，大量的新玩家涌入让这刚刚形成的联盟土崩瓦解。
相对应，最近一年百度的股价从90多一直升到了190的历史高点。
接下来的百度的股价怎么走？ 也许我们不是看百度又推出了什么无人驾驶自行车，不是度娘是不是结婚了，又有什么新鲜的玩意，百发的金融有什么新产品了。 而是深入这个生态圈子，去黑市上看看，百度竞价单页这个圈子又出现了什么新的变化。 这是百度的核心业务和收入命脉。
**** 给我们的启示
曾经认识一个百度公司的高管，在一个很私下的场所一语道破了百度的商业本质：“三四线城市五六十岁的人”。 大家信然。 这句话说的并不那么准确，五六十岁并不是真正是说中老年用户，而是指一切没有分辨是非真假能力的用户。
TOMsInsight给华尔街不少对冲基金做过百度的分析，大家公认的最大的风险就是这个信任危机到什么时候到来，当信任危机出现之前，百度的生意看上去是那么的完美。 而就如电视广告，一切可能都在一瞬间发生。
对我们来说，了解真正的百度，并不用盲目追捧，更不能一味的打击，了解事实认可事实接受事实才是一种气度和进步的态度。 百度的平台造就了特殊的生态系统，而这个生态系统也成就了百度。 正确的去了解这个生态系统，才能认识清楚真正的中国互联网。 而事实才是创新和进步的基础。
互联网只尊重创新和进步。

** [[http://chuansong.me/n/658199][中国互联网黑市门槛(四) 网络彩票]]
互联网发展二十年，日新月异，让很多在这个行业里面沉寂的人难以琢磨。我们跟随着新概念、新思维、新观点，也尊敬或唾弃那些被时代淘汰的竞争者。有时候会觉得在互联网行业就如冲浪，一次次的浪头，成功者把握住节奏，失败者拍在岸边。


但是万变不离其宗，互联网上根本用户需求，好像从互联网诞生那天起就没变过。比如典型的3G需求：Game、Girl、Gambling(游戏、美女、赌博)。而作为变现商业模式最直接的博彩，更是作为互联网的第一代Key Application，都很难说是互联网推动了博彩，还是博彩推动了互联网。

2014年世界杯期间，足球竞猜型彩票走入大众生活，各种社交媒体上的段子和分享让越来越多的人尝试了一把“赌球”的快感。随着世界杯的结束，有多少用户能转化成忠实用户或者博彩业最看重的VIP用户(国内称之为“问题用户”)，我们还没有具体数据，但是从资本的吹捧和行业的热点轮换来看，新的一轮网络彩票的风头也在逐步形成。当然这是合法部分，但是冰山的水下又隐藏着什么猫腻呢?又有哪些黑市中不为人知的秘密呢?

TOMsInsight继续我们的互联网黑市的分析报告系列，今天的主角是：网络彩票。

*** 彩票行业全貌分析

我们先从彩票业的全貌来分析。

中国彩票业有超过20年的历史，已经形成了非常成熟产业链。彩票有其特殊性，由于某种意义上讲属于博彩业，只有国家(福彩、体彩)有发行彩票的资格。赌博利用了人性中非常特殊的一部分，再加上中国文化和特殊国情，所以彩票从出现那一天起就意味着高发展和高利润，也意味着相应的社会问题。所以彩票的产品和游戏规则，一直都是在争议中发展。

目前来说，国内的彩票可以分成四类：


*** 即开型：
2000年前，几乎所有的彩票都是即开型。有些朋友可能记得在20世纪90年代，每个三四线城市都会因为即开型彩票活动而兴奋：现场发行，当场兑奖，奖品包括摩托车、电视机、照相机等当时大件，后来又出现更大的现金或实物。那些年，每个小城市都流传着很多和即开型彩票相关的故事：有人一夜暴富，有人倾家荡产，压抑了多年的民间赌博需求有了整体的释放。2004年西安体彩宝马案之后，大奖组即开票被终止。

目前发行的即开票主要有福彩的“刮刮乐”等，奖额较小。2013年即开型彩票销售351.91亿元，同比减少30.33亿元，下降7.9%，占整体彩票的11.7%，但是也是四种类型彩票中唯一下降的类别。

*** 乐透数字型：
2000年后，计算机技术的发展让电脑联网型彩票有了技术基础，乐透数字型彩票成为了主力军。福彩和体彩开始发行大量的通过选取数字的组合或者排列中奖的玩法。目前这种彩票占彩票业销售额的半数以上，包括销量第一的双色球(单品种2013年销量518.14亿，站整体彩票销售额的16.7%，仅仅是双色球单产品，就秒杀掉了竞猜型、即开型、或视频型的彩票。)

值得一提的是，乐透数字型彩票里面有一个分支，叫快开型彩票。以时时彩为代表。这种彩票一般10分钟一开奖，24小时几乎不停，而且有一些产品在夜场会5分钟，甚至更短的时间一开。快开型彩票是一个新产品，有不少争议。而且在网络彩票中黑市中占据了八成以上的流量。(在后面我们会单独大篇幅分析此类型在网络上的形态)

*** 竞猜型：
竞猜型彩票是由体彩发行，对体育赛事进行竞猜的彩票，主要是足球，篮球。从形式上来看，让很多人都会想起来“赌球”，但是由于不存在“走地盘”(在赛事进行中变化的赔率)，所以已经阉割掉了赌球中最大的魅力。

竞猜型彩票是后起之秀，在2001年国内才开始发行足球彩票，接下来几年内品种并没有过快发展，主要是竞猜型彩票的玩家和传统的彩票玩家并不是同一群体。近几年，竞猜型彩票赢来了高速发展，2013年竞猜型彩票销售338.42亿，同比增长26.2%。

*** 视频型：
视频型彩票特指“中福在线”，“中福在线”是个什么东西呢?也许有些朋友还记得前几年青岛“中福在线”中心购买豪华游艇，引起社会正义的新闻。“中福在线”从诞生那天起，就最受争议。因为这玩意实在和拉斯维加斯的老虎机，实在太难区分开了。

“中福在线”是一种联网即开型彩票，和普通的即开型彩票不一样，由于是联网的，所以返奖率固定，中奖额是动态变化的，可以是大额奖金。最重要的是，仅仅可以在一个固定的场所(中福在线大厅)用特定的终端投注机玩耍游戏。而游戏的设置也主要是以刺激过关性反奖型为主，这也是博彩业游戏机中最主流的方式。绚丽刺激的游戏画面，甚至“中福在线”大厅的装修布置，都有极强的目的性。

“中福在线”全国有1000多个大厅(北京目前没有)，2013年销售额289.39亿，同比增长29.1%.也许去过“中福在线”大厅的人会有体会，如果从玩家角度看和赌场的区别，只能说返奖率才65%，远远低于赌场吧，别的好像也没啥区别了。

----------------

综上，彩票业在国内经过二十几年的发展，已经成为了一个非常成熟的产业，特别是近十年的高速发展(10倍销售额)，更让销售网络遍布全国。



彩票业也不断开辟着除了传统销售网点以外的销售渠道，比如2002年SP火热时期的短信购彩。后来淘宝上出现的各种代购彩票，和目前几乎所有的互联网巨头都争相进入。

而网络彩票的发展，又是什么的情况?为什么我们要放在互联网黑市分析呢?我们接下来看。

*** 网络彩票商业模式和风险

互联网作为彩票的销售渠道，是典型的利用流量切入传统行业。我们可以看到下图，跟踪拉斯维加斯的最大的5个博彩公司的线上线下销售数据，线上销售主要以非即时反馈为主(彩票类，赌球类)，而作为棋牌游戏类，网络的体验完全就不如亲临其境了。通过网络销售彩票已经是博彩业的一个常态。


很多人都是从这次世界杯开始知道竞猜类彩票的，也是通过各种app在手机上直接下注。可见互联网对彩票的传播推广效应和作为渠道的结合。不少平时不关注彩票的人，也是从这次世界杯开始通过网络购买彩票的。

但是世界杯只是一个营销红利，在中国的博彩需求处于长期压抑的状态情况下，世界杯期间的竞猜类彩票销售情况并不能说明什么趋势和前景，也并不能意味着又多么美妙的趋势，如果就此来讲述“从此用户消费使用习惯养成”的故事等等，就更可笑了。我们从下面的流量曲线可以看出来，世界杯结束后，需求立刻回到了原点。


网络彩票是一种被验证过的产品和非常适合的方式，但在国内发展却又不像想象中发展顺利，看似矛盾的结论其实并不矛盾。

因为目前网络彩票，实在有太多问题了。

2012年12月28日财政部印发关于《彩票发行销售管理办法》的通知，第二章第五条所写，彩票“发行方式，是指发行销售彩票所采用的形式和手段，包括实体店销售、电话销售、互联网销售、自助终端销售等”，所以，互联网彩票业只是一个销售发行渠道，就如实体店、自助终端一样。换句话说，网络彩票，只是代售渠道，任何一家网站都没有自己合法的设计发行资格。

由于彩票的总发行费用只占销售额的15%，还包括两大彩票中心的运营成本，其实网络彩票的可能拿到的利润极低，只能占据销售额的5-7%，甚至更低。

在此通知之前，淘宝和其他一些网站都一直在销售彩票，这个通知只能算是一个市场正名。但是由于利润低和一些其他原因，一直没有铺开市场。铺开市场大概是2013年的事情，在500彩票网上市前一系列的资本动作，和上市以后投资者对互联网彩票行业加大了关注和炒作。而国内的一些互联网巨头公司(阿里、腾讯、百度、网易、新浪、奇虎360)，为了资本的追捧和预期，纷纷推出了自己的彩票销售渠道，或者通过收购占位。

其实行业内的人都知道，这里面有一个极大的风险，就是牌照问题。按照惯例，互联网彩票业有一个牌照的预期，牌照出来之前，爱怎么玩怎么玩，但是一旦牌照出来，拿不到牌照怎么办?所以这个风险导致了并不是所有的公司都敢在这个方向上投入。目前只有两家网站是被批准销售彩票的(2012年9月，财政部批准中体彩中心委托中体彩彩票运营管理有限公司、深圳市易讯天空网络技术有限公司开展互联网代理销售体育彩票业务试点工作)，前者即中国体彩网，后者为500彩票网。

不赚钱，又有这么大的风险!为什么还进入到这个领域呢?网络上那么多大大小小的彩票网站，为什么都如雨后春笋般。

因为很多互联网彩票网站不在乎牌照，也不会赚不到钱，就是“吃票模式”。

*** 网络彩票灰色模式

什么是吃票模式?这已经涉及到灰色产业链部分了。

由于网络彩票仅仅是代购，那么用户在网络上购买彩票后，代购的互联网公司要去国家的体彩或者福彩中心购买对应结果的彩票，在行业里面叫：出票。

比如用户在XX彩票网上购买了一张双色球彩票，那么XX彩票网就要在合作的特定福彩网点购买这张特定数字的双色球彩票，并且记在用户名下。一旦中奖，用户凭借自己的在XX彩票网登记的信息，去特定福彩网店去领奖。

我们继续假设这个故事：XX彩票网是众多的彩票网站之一，负责人B哥经营了好几年后，发现上半年卖出去1000万面值的彩票，国家福彩体彩中心给的代售费大概只有销售额的10%，由于自己没有牌照，只能是找特定的网点合作，只有大概5-7%的利润回款，乐观点也就是70万。再扣去在各种网盟购买流量、SEO的费用，自己网站的技术维护和服务器成本等等，只剩下20万。

眼睁睁的看着1000万的流水，却只有20万的利润。负责人B哥开始转动脑筋了：“这半年来，XX彩票网这卖出去的1000万彩票，根本就没中过大奖，都是些小奖。如果算算，XX彩票网总的中奖额度只有100万左右。如果用户在网站上购买彩票后，我不去彩票中心购买了，中奖的钱我自己打给用户，还省的用户麻烦领奖了!更直接，更为用户考虑!”

就如同最近网上很火的那位辩论的哥们似的，B哥不仅仅给自己找了个完美的商业模式，还能帮自己的非法生意找到理由。于是B哥的XX彩票网就走向了“吃票模式”。大家通过这个例子可能已经看清楚了，吃票就是自己坐庄，用户购买的彩票的钱完全给了这个网站，这个网站也直接负责发奖。

我们接着来假设这个故事：B哥快乐的又干了半年，这半年还是卖出去1000万的彩票，这半年没有人中大奖，发出去100万的奖金，再扣去维护成本，盈利850万。哇塞，一样的销量，一个模式的变化盈利就从20万到了850万!

B哥又开动脑筋了：“现在这样的吃票模式还是风险太大了，没人中大奖可以，万一中了就惨了，现在双色球的奖池已经2亿多了，万一下半年，我的用户有人中了，我只能跑路了!但是拿着这几百万跑路，是不是太少了点?”

于是，接下来B哥又开始出票了，但是这次XX彩票网所有的彩票都登记在B哥自己的名下。果不其然，没出2个月，XX彩票网上有一个用户的彩票直接中了双色球5000万，B哥二话不说，飞速领奖，迅速跑路!然后现在在欧洲某海边别墅快乐的生活着。

可能这就是大多数彩票网站经营者从正规到灰色的过程。

下图是我们跟踪10家网络彩票销售网站(非上市互联网巨头)双色球产品，随机号码与历史中奖号码重复率：



就是说我们有时候经常在网络上买彩票，很多朋友懒省事，喜欢随机几注，但是随机出来的数字，大多都是和历史上的中奖数字重复的。没错，有人说彩票是独立事件和历史结果无关，但是毕竟双色球历史上从来就没出现过完全一样的中奖号码。这也意味着，你在这些彩票网站上随机出来的号码，根本不可能中。

再换句话说，这些网站根本不会把你的随机号码出票!至少我们调查的10家里面，有8家如此。

TOMsInsight的一名数据分析师针对于一些互联网巨头的网络彩票跟踪了半年之久，发现也存在吃票的情况。和中小彩票网不同，这些巨头的推荐号码更隐蔽，通过一些算法计算出不中奖的最大几率进行推荐而不是单纯的推荐中奖过的号码。

所以各位朋友，在网上买彩票，尽量自选吧!

*** 网络彩票黑色模式

看到有些人会有疑问，吃票这么令人发指的事情，都只能算灰色模式?那彩票的黑色模式是什么!!

有一种彩票，和国外发行的彩票没有任何关系，完全是由私人坐庄，私自控制返奖率，被称之为“私彩”或“黑彩”。黑彩有很悠久的发展历史，从互联网并没有流行的时候就已经开始了。最早从香港传入南方内地，后在东北三省发扬光大，慢慢全国流行。

目前行业内比较保守的估计官方彩票和黑彩的销售比例大概四六开，也就是说“黑彩”在国内保守估计大概有5000亿的规模。

我们接着用B哥来说明。

在欧洲某海边别墅快乐的生活着B哥过着纸醉金迷的生活，很快把几千万挥霍大半。这样下去不行啊，B哥又想开始自己的老本行。

B哥开始考虑新的创业计划：“再做一个和之前类似的彩票网站吧?由于之前XX彩票网是由正规的彩票网站发展的，后来才走入歧途，所以XX彩票网从无到有流量人气也积累了2-3年，现在可没有那么工夫去等待2-3年，赚钱速度太慢了。”

于是B哥开始考虑做一个黑彩网站，和传统的线下“黑彩”一样，用高反奖率来吸引彩民。B哥的新网站上线了，花了几百万推广，但是没想到的是，完全没有人气，这是怎么回事呢?

是这样，传统的黑彩一般都由地方社会大哥去来罩着。而十几年的发展，已经形成了非常直接的信任关系。而黑彩的彩民也和官方发行的彩民不同，ARPU极高，是一批专业彩民客户。

“客户通常都是关系介绍的，代理网络会对每个客户的姓名、家庭住址、工作单位进行建档，对偿还能力做出准确评估。其次，每个客户都有担保人，代理会在彩金中给担保人一些好处，但担保人必须为客户承担责任。如果客户不能承担偿还能力，就由担保人偿还。”B哥经过一段时间的经营后发现。

这种模式就和民间借贷一样，把中国传统的线下信任网络发挥到极致，并相互制约。而互联网根本就不具备这种长期积累，或者利用社会资源积累下来的信任关系。

B哥郁闷了好久，眼瞅着钱快没了，做传统的黑彩玩不转，只能做回老本行，但是老本行速度又太慢。几个月的思考后，B哥妙手偶得，又找到了既能利用官方彩票的信任，又有黑彩的灵活性和暴利的互联网黑彩的新模式：那就是快开型黑彩。

之前我们已经介绍过快开型彩票，2013年全部产品加总销售额631亿，占整体彩票业的20.4%.但是在互联网“黑彩”中，快开型彩票几乎占据80%以上：



以“重庆时时彩”为例，白天10分钟一开，夜场5分钟一开，一天就能120期!

“哇塞，之前吃票别的彩票产品，几天才一期，急死人。现在一天就120期，简直太爽了。而且虽然时时彩额度小，但是吃票赚的是流水，是交易额。最关键的是，完全和官方的时时彩产品同步，解决了信任问题!” 
 B哥完全兴奋起来了。

接下来有互联网特色的特殊网络黑彩产生了。B哥采取了和官方的快开彩票完全一样的结果，解决信任问题，大量吃票，又回到了大量揽钱的阶段。

但是没多久，又出现问题了。由于B哥比较贪，大奖完全不付，所以快开的吃票网站很快就能被人发现，经营不了多久，只能打一枪换一个地。这样的纯骗的模式赚钱虽快，但实在是太操心了。没法继续纸醉金迷的生活啊。

于是B哥又继续把中国互联网的最精髓的部分拿出来了：代理。招一些代理去做，分配利润给代理，自己坐收其成!

接下来的故事可能大家能想出来了，B哥很快出局了，代理们都学会了这种方式，网络快开型黑彩也开始了在中国互联网上的真正的发展。

群体智慧远远比B哥一个人的天才要可怕的多，经过几年的发展，国内各种各样的黑彩层出不穷，各种骗局极其高明。目前大概有下面几类：吃票(B哥的老模式了)、大客户模式(通过黑市上购买数据，找到特定的客户，推荐号码给客户，然后中奖，打造信任，让客户一点点的深入，最后赚一笔大的跑路)、散户模式(通过大流量引入大量的客户，针对每个客户都有特定的算法开票，逐步引入)、平台群(开大量的黑彩平台)

而黑彩的竞争也到了白热化：DDOS，黑市数据、病毒、黑链引流等等，十八般武器都进入到了这个利润极其高的黑产中。甚至百度搜索“时时彩黑彩”都能找到大量平台和软件出售!

当然黑彩中还有别的形式，比如模仿“中福在线”(目前在百度上打广告的“中福在线”均属非法)，比如更接近赌博形式的玩法。(接下来TOMsInsight会有专门针对网络棋牌赌博，和赌球的分析报告。)，都属于完全的非法行为，其中大多数都是骗局!

----------------

最后奉劝大家一句，远离黑彩，切记!切记!如果通过网络购买正规彩票，尽量在中国体彩网、500彩票网购买。如在一些互联网上市巨头购买，尽量自选!远离中小彩票网站!

----------------

我们也能从彩票业和B哥的例子看出，任何一个传统行业都会有那么多年发展的沉淀和积累。有时候这种积累被无形的手调控着，成为一种平衡，哪怕是黑彩。辩证法强调：存在即道理。

没错，互联网是进步，是未来。但如果粗暴的进入一个行业，结局却不会那么乐观。仅仅不被接受或碰壁还算是好事情，有时候无意中破坏了行业的生态平衡，带来的后果可能会无法控制。

*** 给我们的启示

在古老的中国，七十二行不管三教九流每个行业都有个祖师爷，每个行业也都有特殊的行规。拜祖师爷、遵守行规，不仅是行业抱团和经验积累，更多的是从业人员踏实的匠心和传承的敬畏心。

互联网的发展，特别是最近几年移动互联网的发展，给很多行业带来了颠覆性的冲击。而几乎每一个互联网创业者，也都虎视眈眈的注视着各个传统行业，张口闭口的都是颠覆。

也许在喊出颠覆之前，需要全面的深入了解这个行业。静下心思考是带来进步，还是只带走利益。这不仅仅是我们互联网人应有的敬畏心，也是对用户的一种尊重，更是互联网在各行业长期、共赢发展的必要条件。

互联网，是未来发展组件，不是牟利工具。
** [[http://chuansong.me/n/702536][中国互联网黑市门槛(五) 攻击敲诈勒索]]
我们喜欢谈论江湖、向往江湖，向往那种不拘：人生沉浮朝代兴衰、美人如玉爱恨如歌、斜阳落影拔剑生死。每个人都有自己心中的江湖世界。


互联网世界更是一个江湖。我们写完代码搬完砖后津津乐道中国互联网三大帮派的历史恩怨，邪教数字公司的剑走偏锋，新兴粮食帮的快速扩张;我们喜欢把这个江湖中的英雄称之为“大佬”或者“大咖”，谈论着他们的奇闻异事与贪镇痴;我们喜欢江湖故事，大家会有滋有味的看着某个帮派的新品发布会，或比武论剑;我们喜欢参加各位帮派聚会，江湖八卦新闻那是必看;我们不断的学着黑话，和特定的英文单词来武装自己，在刚入行小弟面前，充当江湖老鸟：“那一次在肉饼的review会上”、“pony当年可是有这个idea的”、“code写的不错，但是你得加点花指令迷糊下破解者啊”。

我们嘲笑着那些没落的帮派，什么诺记，什么巨硬，什么破18摸，看着那些最近不断驱逐兄弟的帮派，或心中暗爽或莫名悲凉;我们最喜欢的还是想方设法加入走红的帮派，然后骄傲的喊一声：我厂、我司、我鹅!感觉从此入了山头，有了底气。我们书生意气，挥斥方遒，指点江山，激扬文字，粪土当年万户侯!

终于有一天，我们觉得在帮派混也没啥意思，也就那么回事。不如下山单干，自己成立一个帮派，几个兄弟几把剑，行侠仗义，改变世界!当然，主要也是看到那些不断成立的小帮派，才半年，就获得大财主资助，要钱有钱，要名有名的，比朝六晚九的给别的老大干活强太多了。

于是约了几个兄弟，拿着这些年在帮派混分到的所有的碎银子，准备好好闯荡一番。但是万万没想到的是，第一天下山住店，就被下三滥的土匪强盗破窗纸用迷香迷翻，抢走了所有的碎银子、宝剑不说，还扒光了威胁要在身上用靛青刺下SB两字，再勒索几百两银子!这TMD和之前想象中的行走江湖落差也太大了吧!当年在中国互联网前三大帮派的“我厂”山头混了N年，T9高工啊，怎可能遇到这样的侮辱!

这个故事演义了点但是不偏激，互联网确实是充满了机遇挑战，中国互联网也逐步的走出一味模仿，开始创新和颠覆。但是不可否认的是，中国互联网也有其特色：网络攻击敲诈勒索，从互联网在国内落地的第一天开始就伴随着成长、发展、创新、壮大，最后形成一条让人恨之入骨又不可奈何的产业链。

TOMsInsight继续互联网黑市的分析报告系列，今天的主角就是：攻击敲诈勒索。

*** 网络攻击敲诈勒索的发展

本分析报告把攻击敲诈勒索的个人或团队称之为：攻击者。而被攻击的网站称之为：受害者。

对于所有的中国互联网中小企业主、创业者、站长来说，网络攻击敲诈勒索都是横着眼前的一道非常现实的关卡。为什么我们要把“敲诈勒索”要和“攻击”放在一起呢，敲诈勒索的法律定义是“以非法占有为目的，对被害人使用威胁或要挟的方法，强行索要公私财物的行为”，现实社会中由于人与人之间关系的复杂，可以通过各种方式来抓住把柄、或者依仗势力进行威胁要挟。而对于互联网而言，一切反而回归到最简单，那就是先攻击，后敲诈勒索。

我们来看看网络攻击敲诈勒索的历史：

在中国互联网发展早期，大概96-97年，当大家还都拨号上网，没有免费邮箱的时候，互联网服务提供商一般在提供电话拨号上网服务的同时，送一个邮箱。由于当时存储空间昂贵，这一个邮箱会有容量限制，超出限制，就要收费，一起计算到电话费中，而这个费用是非常贵(根据地域不同，一般1k一块钱)，所以如果是超出了几百K几M，就是几百几千费用。

早期网络大家也就是泡泡BBS玩玩MUD再就是聊天室，不管是灌水杀鬼子还是聊天泡妞，经常发生争吵有火气，有一些人就开始去“炸”对方的邮箱，其实很简单，往对方信箱发一个几百K的邮件，就让人抓狂。那个年代，“我炸了你邮箱”是一句很牛逼的话!大家纷纷把自己邮箱地址保护的比密码还小心。

有一些人因为争风吃醋，伪装成mm在聊天室套出受害者邮箱，威胁炸掉，让受害者离开特定的BBS或者聊天室，就成了当时的流行套路。而这估计也是中国互联网形态里面最早的攻击勒索敲诈吧。

在2002年之前，网络攻击敲诈勒索行业发展缓慢，主要是那个年代的中国互联网经济还处于烧钱状态，直接变现机会很少。稍微成点规模的敲诈也就存在于网络新闻领域(后面我们会具体分析)，所以那个年代的互联网记者地位那也是相当高。但是2002年以后，网游和电商的发展让互联网有了直接变现的渠道，所以也导致了攻击敲诈勒索行业也赢来了自己的辉煌。

下图是我们调查了7个创立在2000年前的网站，在这15年被攻击敲诈勒索的次数，由于网站类型和规模不同，我们通过算法处理加权平均，仅仅供大家参考趋势的变化(可以看出2014年净网行动还是很有成效)：



到了最近几年， 这个产业已经形成规模，从低端到高端都有细分产业链的形成。大概分类成：人肉型、信息型、技术型、创意型。接下来我们逐一分析。

*** 人肉型攻击敲诈勒索

人肉型是指那些纯凭人工完成的攻击，这也是中国互联网的一大特色。近几年有一些人肉型攻击者，通过QQ群、YY群组织几千人甚至几万人的大规模团伙，有组织有纪律的去完成任务，形成极大的力量并有独到的优势来骗过代码。

恶意购买：很多电商网站都有货到付款的服务，特别是百度生态圈的单页电商、或者是一些特殊垂直行业电商网站(例如成人用品)，通过物流公司的代收费业务，货款由物流公司代收。人肉攻击团伙采用下假单的方式，由于找不到用户，只能把邮包再退出来，一发一退对于受害者来说就是几十元的成本。接下来攻击者就会去受害者和谈，一次性或者每月收“广告费”、“公关费”、“营销费”、“顾问费”等打着各类名义的敲诈勒索费用。

恶意差评：差评师主要存在淘宝网，大家可能比较熟悉。差评师对卖家伤害很大，皇冠级别的卖家来说几个差评起不了多大作用。而对于心级卖家来说，几个差评基本上就宣布店铺倒闭了。交纳了保证金的卖家都是诚心想要把网店做好，为了自己的生计，多数卖家会选择忍气吞声的交钱。差评师会注册很多小号，拍店铺商品的时候十分爽快，但买回之后，问题就一连串地找上门来，称要给你选差评，店方老实地给了钱还好，对于店方比较强硬的，差评师们死缠烂打，团伙作案，大规模作案，直到就范为止。

恶意投诉：恶意投诉主要针对京东、亚马逊等平台的第三方加盟店，这些平台并不存在淘宝那么核心的信用等级机制，但是非常看重加盟店的信用口碑。攻击者一般会用几十个甚至上百个ID去受害者店铺去购买，然后去平台投诉买到了假东西、不开发票、存在欺诈、服务不到位等等。由于投诉众多，平台一般还是会对加盟店进行审核整治，甚至撤掉资格。由于成为京东、亚马逊等平台的加盟店都会有一定的资质审核和保证金要求，所以店主更多的时候也希望息事宁人，交保护费了事。

恶意点击：恶意点击是针对网站的广告投放。比如说CPC广告，是按照点击计费，我们之前也贴过百度的CPC广告数据，每一次点击都几元甚至几十元。攻击者采用人肉战术，每天几百几千人去点击受害者网站的广告，直接造成大量的广告费用浪费;再比如在app分发领域的CPA激活，攻击者定向下载app再卸载掉，造成极大的广告费用浪费，对中小创业者来说是致命打击。过不了多久，被攻击者就会收到一个QQ消息或者短信：“每天你都损失几千元广告费啊，不如给我们每日一千，我们保证不捣乱了，行不?”能把人气的肝颤。




我们用实际的例子举例：某互联网巨头T9高工F哥准备创业了，F哥看准了目前火热的“小资生活”概念单品电商，准备包装出一个高大上的品牌专卖滋补类农产品，例如：山药、紫薯等，专注品质，定位北上广高收入白领，走精品小资路线。

F哥和几个合伙人拿出来几十万创业，经过几个月的准备网站开张，不仅有自己的独立网站，也同时在淘宝、京东、亚马逊、微信小店、口袋通同时开店。

没几天，F哥的独立网站支持货到付款的订单就发现几乎全部都是虚假订单，看上去每天几千个订单，送过去都TMD没人收!电话确认吧?招了几个小mm客服专门确认，但是确认没问题，送过去还是没人收!

这还没完，自己的淘宝店全是差评，京东、亚马逊、微信小店、口袋通也被人疯狂的投诉!天天去处理这些投诉都处理不了，眼瞅着就要都被下线了。更惨的是，自己在百度移动端、微博上投的广告，每天消费几千，好像没几个有用的IP，而且几千的预算几乎在一瞬间就被消耗了。

接下来F哥接到了一个匿名短信：“哥们，看你做的品牌挺高大上的，给我们兄弟一个月2万块，从此就不捣乱了，行不?”F哥哪见过这样的流氓，直接气炸了!但是报警吧，没啥用。防范吧，好像也没啥好办法，两败俱伤的，耗不起啊，还要去拿融资呢，算了，破财消灾吧。

但是这才是F哥的遇到的最简单的攻击。

*** 信息型攻击敲诈勒索

人肉型攻击敲诈勒索几乎没有什么技术门槛，就是组织大量的人有纪律的捣乱。而接下来信息型的攻击敲诈勒索，就开始有一些门槛了。

媒体负面信息：媒体通过负面消息敲诈好像已经不算什么黑市的分析范畴了，已经成为了一个行业常态，所以我们在此也不再拿出来多说什么。值得一提的是，大多数媒体负面消息并不是媒体本身所为，而是一些记者、编辑。在黑市上，很多网络媒体的记者、编辑直接明码标价负面新闻，而大量的攻击者在黑市上去购买这些发文权，有目的的去攻击，最后敲诈勒索的也是这些攻击者，记者编辑只是产业链中最底层的一环，而网络媒体只是被利用而已。

水军负面信息：水军负面消息是用大量的ID去发帖子、博客、知道问答、微博等，在网络上给某一特定受害者造成负面影响。在2010年之前，这些信息主要都存在与论坛上，比如著名的天涯论坛，如果经常上的朋友甚至都会收到一些“专注于网络报仇十几年的公关公司”的广告。但是在2010年以后，攻击者很少采取用这些的大量水军负面消息了，而这些手段主要由一些公关公司使用，用在同行之间的攻击，这是为什么呢?

攻击敲诈勒索关键是为了钱，受害者交了保护费后就需要放过，不然怎么能有连续收入。但是水军负面信息，发起来容易，删起来难。比如天涯论坛信息后不能删帖，必须版主完成，而水军采取发帖机发帖，删除有很大的难度。目前升级成SEO负面消息手法。

SEO负面信息：SEO负面消息主要是指攻击者利用搜索引擎：我不发你很多负面消息，只需要在百度上搜索你的品牌或者关键词，前几页都负面信息即可。这足够造成破坏，而且这些前几页的负面信息都是攻击者可以控制的，说删就删。这又是怎么做到的呢?主要是使用黑链。

黑链是SEO手法中相当普遍的一种手段，是指一些人用非正常的手段(黑客攻击或内鬼出售)获取的网站的反向链接，最常见的黑链就是通过各种网站程序漏洞获取搜索引擎权重较高的网站权限，链接自己的网站，其性质与明链一致，都是属于为高效率提升排名，而使用的作弊手法。黑链在互联网黑市上明码标价的售卖，所以攻击者很容易去购买。(TOMsInsight以后会推出分析报告专题介绍黑链)

接下来攻击者简单的通过程序模版加数据抓取，制作一批新闻类、博客类的网站，通过关键词优化和黑链技巧，快速的把自己网站上的一些新闻在每一个特定的关键词上(一般是受害者品牌相关词)优化到前几页，这样，完全可以控制信息，收钱后秒删。

下图可以看出来，大多数黑链目前链接存放时间都在40天之内，而这个时间绝对只能是恰好做好优化后就删除，这些黑链的作用也很明显了。




我们接着用F哥举例：F哥咬牙切齿的每个月交了两万的保护费，没想到又出来一个攻击者，攻击者越来越多，每个月的保护费开支都要十几万了。好在F哥和合伙人起早贪黑的拼命干，定位准、包装到位，竟然也没赔钱。

但是F哥想，这样下去不行啊，玩了有一年多了，不赚钱啊!都TMD给一些流氓打工了!灵机一动，我们可以赚风投的钱嘛!反正这行都是这样，不赚钱就只能玩资本游戏了。再说了我是著名的“我厂”T9高工出身，项目新颖并切合热点，前景有想象空间等等，整合投资人的口味，先骗几百万花花，自己洗出来一部分是正道!

说干就干，F哥放出消息，接受各种科技媒体采访，见投资人。但是几天后F哥百度了下自己的品牌关键词，直接楞了。几乎一夜间，百度的前几页全都是负面新闻啊：“什么山药里面有一尺长的毛毛虫啊”，“紫薯是染色的吃完嘴唇都紫，亲嘴还相互染啊”，甚至还有F哥本人的“T9高工时期曾经性骚扰公司打扫卫生的大妈啊”。

几天后，F哥收到匿名短信“哥们，你弄投资挺爽的，但是先给兄弟一点花花呗，反正都不是咱们的钱?对不?”F哥直接气疯了。

不过，更气人的还在后面。

*** 技术型攻击敲诈勒索

技术型攻击敲诈勒索和之前都不一样，攻击者利用黑客技术，敲诈勒索的金额放大很多倍。当然，这些技术的运用，也有更大的成本，这里面就包括网络攻击的第一常规性武器：DDOS。

DDOS：DDOS指分布式拒绝服务攻击(DistributedDenial of Service)，借助于分布式技术，将多个计算机联合起来作为攻击平台，对一个或多个目标发动攻击，从而成倍地提高拒绝服务攻击的威力。在此我们不过多的探讨技术层面，以后TOMsInsight会有专题分析针对这国内第一网络常规性攻击武器。大家可以这样理解：用大量的虚假访问，占据了被受害者网站的带宽，让真实的用户没法登陆。春运时候的火车票订票网站经常上不去吧?这就好比是一次DDOS的效果。

DDOS攻击在国内有两种情况，一种是黑客控制大量肉鸡网络(被黑客控制的电脑)进行攻击，或者是拥有带宽资源的IDC机房背地攻击。后者多出现在一些很特殊的情况中，而对于网络攻击敲诈勒索，主要是前者。

在这个产业链中，黑客一般不会直接参与攻击敲诈，只提供肉鸡网络的使用权;DDOS攻击服务提供商租用肉鸡网络进行攻击;而攻击者去购买DDOS服务。所以这种三层模式中，攻击者的成本是相当的高，特别是一些有规模的网站都有足够的带宽去扛DDOS。所以与之对应，一旦到了DDOS攻击的地步，相对的敲诈勒索金额也会随之增加了。

对于一些特殊行业的DDOS的攻击敲诈是可以产生暴利的，特别是讲究实时运行的网站，例如之前一段时间火热的比特币交易平台，或者电商网站的抢购时段。

黑客攻击：DDOS的攻击黑客是不屑于参与的，但是黑客也会直接充当攻击者，主要是对网站的用户数据进行入侵并获取。一旦获取了网站的数据库，就会直接联系改网站进行“赎回”，并威胁一旦不赎回，就会进行“撕票”。

“撕票”的意思就是公开受害者网站的用户数据库，由于此威胁是一次性的，有些网站还真的不会赎回数据库，例如历史上有过几次著名网站(CSDN、天涯等)的数据库泄露，都是属于“撕票”。

但是渐渐地，由于金钱诱惑，黑客这个圈子也开始变得鱼龙混杂，很多攻克了数据库的黑客，不遵循“赎回”和“撕票”的古老行规，而是直接卖给受害者的竞争对手获利。


我们继续用F哥来举例：F哥花了50万把负面新闻都拿掉了，也利用自己的三寸不烂之舌忽悠到了天使投资500万，开始了高举高打。继续着不盈利，烧着钱，寻找着各种创新概念，刷着假数据，忽悠A轮投资的典型中国互联网精英创业之路。

A轮谈妥，马上到位，处于关键期。没想到的是，F哥的网站开始被DDOS攻击，而且攻击的时间点都是自己网站搞秒杀活动的关键点。更可气的是，自己的用户数据库不知道怎么被泄露了，有人威胁说必须拿出来1000万赎回，不然给每一个客户发一份邮件外加短信声称是F哥网站出卖用户信息。F哥傻眼了，这是搭上自己名声信誉再加法律风险的问题了。

F哥想着这几年创业，辛辛苦苦却一分钱没赚到，还花出去很多没法见光的钱，承受着投资人、合伙人怀疑自己洗钱的眼光，留下了委屈的泪水，也体会到了“江湖险恶”。

*** 创意型攻击敲诈勒索

以上是目前基本的攻击手法。但攻击敲诈勒索行业发展至今，开始出现了各种创意型的手段，各种组合拳的运用，让人防不胜防!

比如“在黑市上购买数据，针对一些个人深度数据的攻击与个人敲诈勒索”，“对那些可以QQ登陆的网站，通过大量的信封号消息，留下这个网站的名字栽赃”等等。由于我们担心我们的分析会导致一些心术不正的团队学习，在此就点到为止，不再举例。


我们分析了这些攻击敲诈勒索，却没有说破解之道?其实破解之道大家仔细想想，几乎每一个攻击套路都有对应的解决办法。但最根本的破解之道，并不是陪他们玩到底，而是从最根本上坚决的拒绝。

不做亏心事，不怕鬼敲门。对于攻击者来说，攻击也是需要很大成本的。所以对于我们创业者来说，明白江湖险恶，有风险意识，但是坚决的拒绝非法合作，拒绝侥幸心理。静下心做好自己的产品和服务，打持久战，打正义之战，真正被市场与用户接受，先放弃的肯定是攻击者。

这些只是我们需要防范的风险，是我们创新的成本，但绝不是我们创新的专注所在。

*** 给我们的启示

刘慈欣在《三体》中提出了黑暗森林法则：宇宙就是一座黑暗森林，每个文明都是带枪的猎人，像幽灵般潜行于林间，轻轻拨开挡路的树枝，竭力不让脚步发出一点儿声音，连呼吸都必须小心翼翼：他必须小心，因为林中到处都有与他一样潜行的猎人，如果他发现了别的生命，能做的只有一件事：开枪消灭之。在这片森林中，他人就是地狱，就是永恒的威胁，任何暴露自己存在的生命都将很快被消灭，这就是宇宙文明的图景，这就是对费米悖论的解释。

中国的互联网在某种意义上来说，也是这样的一种形态：如果你没有足够的实力，还不断的把自己放在聚光灯下，那只能是玩资本的击鼓传花游戏，博傻而已;对于真正的创业者来说，默默的聚集自己的力量，修炼内功，顽强的活下来、生存下去，才是唯一的发展之路。

也许正如文明，这也是互联网世界的自然选择。
** [[http://www.ityuedu.com/article/32311134041/][中国互联网黑市门槛(六) 社工库的传说]]
任何一个行业都是一个江湖，有江湖就有故事，追名逐利的人喜欢被写入故事，踏实做事的人却希望被隐匿。 久而久之，江湖上的故事越来越虚名浮利，听故事的人也越来越坐井观天。 岂不见无数江湖武侠小说，开篇的人物总是让我们误以为是江湖大侠，看着看着才发现一山更比一山高，到最后才发现开篇人物简直是不入流的小啰啰。 而真正的高人，反而隐匿成传说。

互联网行业也是如此，大家喜欢创造故事，故事也越来越千篇一律的浮躁：什么产品上线7天就几百万用户、什么开发阶段就上亿投资、什么90后霸道总裁颠覆行业、什么大咖的内部分享、从xx看xx的四大趋势、从xx看xx的十大价值、xx的专注力、xx的微创新、xx的平台化、xx的独家专访首次讲述xx辛酸、xx概念的深度解析加独特见解，等等。 翻来覆去，好像也就是那么多东西了。
就好像有些江湖人士，是需要靠卖艺为生，请个会吆喝的帮忙吆喝吆喝，弄个猴子上蹿下跳一下，响啰使劲的敲几下，骗骗几个外行人，撒点碎银子，仅此而已。 接下来大家再接着吹嘘一番，比比谁拿的碎银子多点，动口不动手。 长期以往，有些人招摇撞骗，也竟然成为了一代口碑中的大侠。 久而久之，如今很多江湖人士只是卖艺拿贵客的碎银子为生，如何卖艺卖的更好是大家追求的目标。 那些内功心法，武功秘籍，也都成为了历史，那些大侠们，也成为了传说。
难道江湖不再是那个江湖了么？ 其实不然，浮躁沉沦的只是江湖白道，只是这些大内侍卫，镖局镖师，衙门捕头而已。 而江湖黑道中，黑客技术、海盗精神，继续被追捧，虚浮的商业模式永远不如深度技术被重视，“铁甲依旧在”的情怀还在回荡，而地下产业链相关的进步也在不断的深入，并且潜伏起来暗自发展，为了更大的目标和黑暗梦想。
TOMsInsight继续互联网黑市的分析报告系列，今天的主角是：社工库的传说。
*** 什么是社工库
社工库是社会工程学数据库的简称（Social Engineering Data）。
提到社工库就必须先介绍一下社会工程学（Social Engineering），这个名词最早是在2002年由传奇黑客米特尼克（Kevin David Mitnick）在提出，但其初始目的是让全球的网民们能够懂得网络安全，提高警惕，防止没必要的个人损失。 由于米特尼克在黑客界的传奇地位，很快社会工程学就开始被深入研究并且发扬光大。
社会工程学，准确来说是一门艺术和窍门的集合。 它利用人性的弱点、心理的缺陷，以顺从意愿、满足欲望的方式，让人们上当，或以此为入口进行攻击。 社会工程学的窍门也蕴涵了各式各样的灵活的构思与变化因素，利用人的弱点如人的本能反应、好奇心、信任、贪便宜等弱点进行攻击。 它集合了心理学、社会心理学、组织行为学等一系列的学科，由于其非法性和在很多国家地区都被严厉的打击，社会工程学也变成了一个见不得光的学派。
但是在黑客群体中，社会工程学就是他们的第一方法论和必修课。 离开了社会工程学，黑客们运用的网络技术几乎都没有用武之地。 如果我们用黑客最喜欢的海盗来比喻，各种网络技术可以比作航海、游泳、剑术、而社会工程学即是海盗们的行为准则和创新指引。
那么什么是社会工程学数据库（社工库）呢？ 即黑客在运用社会工程学进行攻击的时候，积累的各方面数据的结构化数据库。 简单的说，社工库是黑客用来记录攻击手段和方法的数据库，这个数据库里面有大量的信息，甚至可以找到每个人各种行为记录（每个人在每个网站上的账号、密码、分享的照片、信用卡记录、订的机票记录、通话记录、短信内容、各种社交软件的聊天等等包罗万象），比如之前有很火爆的查询开房记录的数据库，就是一个典型的极简单的社工库的例子。
那么社工库又是如何产生的，在国内的互联网地下产业链中，又是什么模式的存在，发展又是什么情况呢，我们接着分析。
*** 社工库的发展：数据盗窃
既然是传说，背后就有很多故事，说到社工库的产生和发展，我们就得先从互联网的数据窃取与交易开始说起。
互联网用户数据泄露一直是行业关注的焦点，从最近的京东用户密码泄露事件，到之前的CSDN的数据库完全爆出，再到如家酒店的用户数据泄露，网站和黑客在用户数据上一直在进行着旷日持久的攻防战。 但是爆出来的数据泄露，仅仅是冰山一角，甚至也不到。 而且这些信息其实对于黑客来说，根本没有什么价值。 而对于用户来说的危害，也没有想象的那么大，因为大多数时候这些数据在黑市中几乎都已经是半公开的性质了。
而数据窃取与交易这个细分领域也几乎是地下产业链隐藏的最深的一部分，很多在互联网地下产业链中沉寂了多年的大佬都并不了解此道的相关信息。 绝大多数被盗窃后的网站数据，并不会公开与众，只是交易后进入到地下产业链的其他环节而已。 所以目前到底有多少网站的数据已经被窃取我们没法客观的进行数据分析。 但在互联网黑市中，大家说起来类似的问题，常用的一个词是“十墓九空”，也许这个说法有点夸张，但是也可以参考。
我们从2009年以来，通过黑市的舆情监控和专业网络调查，对互联网每年的流量排名前100的网站（刨去没有用户账号机制的）进行调查，结果如下：

数据窃取产业虽然隐藏的非常深，但是发展历史永久，地下产业链也随之成熟，对于如何把数据变成货币，已经有了非常完整的程序的分工协作渠道。 而其模式相对简单，一般只包括：脱库、洗库、撞库这几个阶段。
在地下产业术语里面，“脱库”是指入侵有价值的网络站点， 把数据库全部盗走的行为 ，因为谐音，也经常被戏称作“脱裤”。 在取得大量的用户数据之后，黑客会通过一系列的技术手段清洗数据，并在黑市上将有价值的用户数据变现交易，这通常也被称作“洗库”。 最后黑客将得到的数据在其它网站上进行尝试登陆，叫做“撞库”，因为很多用户喜欢使用统一的用户名密码，“撞库”也可以是黑客收获颇丰。
在早期的数据窃取过程中，这几个阶段几乎都是由同一个团队、甚至单个人来完成的。 发展到今天，已经完全细化成产业链，很少有人从脱库、洗库一起做了，而变成：定制化模式，或交易化模式。
定制化模式：就是现有下游客户指定的某一家网站，然后聘请黑客去脱库，脱库后获得佣金的模式，在定制化模式中，有很强的黑产规矩即数据属于下游客户，而黑客不可以再次出售，或者在一定的窗口期内不能再次出售。
交易化模式：黑客去某一家网站脱库，脱库后直接在黑市上寻找下家，在这种模式下一般可以反复出售，但是由于风险较大，而且数据真实度和新鲜度不一定能得到保证，又充满了骗局，越来越没落了。
而下游客户定制某特定一家网站的脱库，是怎么盈利呢？
大多数时候，都是竞争对手或者上下游企业采购，而且大多数都是主流互联网产业链中的客户，甚至是传统企业客户。 其实这个模式很简单，想一想在生意场上，这家网站的数据库对谁谁有利，谁就可能是潜在的定制客户，只不过由于很多主流互联网企业或者传统行业很少了解这个地下产业，所以就会有一些中间人，来做中介促成相关的生意，而这些中间一般情况就是黑市里面的买家或者定制客户了。

我们用实际的例子说明：M哥在黑客圈小有名气，技术过硬。 某互联网医疗产品最近要拿投资，深度用户不够啊，通过中间人，辗转的找到了M哥。 M哥奋战了几天，直接脱裤了几家三甲医院的网络挂号系统，历史数据应有尽有，结构化分类一应俱全。 M哥到手200w，中间人到手300w，而这家互联网医疗产品由于用户的激增和数据的全面性，以及对应新产品的虚假运营，多拿来1000w的投资，绝对双赢。
*** 社工库的发展：洗库撞库
如之前分析，不管数据如何贩卖交易，卖给谁，怎么卖，最后黑客手里面还会有一份数据，由于黑市一般都采取定制化交易，黑客们不能再次出售了，所以一般情况下黑客们会用这份数据进行洗库撞库再洗库操作。
洗库主要是清洗这些数据中可以直接变现的部分，但是这样可以直接洗库的就能洗出价值的数据，其实并不多。 一般都是有预存款或者虚拟物品交易的数据库才能洗出来价值，例如：游戏账号、电商账号等等。
更多的时候，黑客将得到的数据在其它网站上进行尝试登陆，叫做“撞库”，因为很多用户喜欢使用统一的用户名密码，“撞库”其实可以收获颇丰。 而撞库和洗库的过程是配合的，黑客使用自己开发的工具、直接数据库匹配登录技术以及配合黑色产业链中的打码机制（之前TOMsInsight报告中有介绍）可以对很多网站进行批量撞库，一旦成功，可以进行再次洗库。
这就好比黑客们拿到了一份没什么价值的网站的全部用户名和密码，没关系，可以用这份用户名密码来尝试着登录有价值的网站嘛，如果能登录，不就可以洗出来价值了么，我们还是继续看M哥的例子。
M哥卖掉了几家三甲医院患者的挂号数据，虽然到手200w，但是也不满足。 想想这几百万条数据，应该还会有别的价值吧。 但是M哥又是一个传统的讲道义的黑客，不会再次出售给别的买家。 只能从这些数据本身来找到价值了。
M哥尝试用这些数据登陆QQ、京东、支付宝、淘宝、各类网游，从而洗掉里面的资产，但是由于各种网络的安全策略的保护，M哥虽然有收益，但是却不多，甚至都不够自己的洗库撞库的网络成本，于是M哥继续沉寂下来，这一沉寂，开辟了一个传说。
*** 社工库的发展：构建传说
在很多时候，社工库都是一个传说，就像海盗里面流传的那笔谁也不知道的宝藏，只有那块已经不知道转了多少手的脏兮兮的残缺的藏宝图才预示着它的存在。 但是社工库却又很客观的放在那里，一直存在，一直沉寂。
除了贩卖数据本身得到金钱上的利益之外，黑客还会把得到的数据进行整理，制作成社工库。 社工库是一个积累的过程，也需要大量的人力物力的去建设，同时还是一个漫长的过程。 开始的时候就像M哥一样，单兵作战的去积累，今天是三甲医院的数据库，明天是旅游网站的数据库，后天的演唱会订票网站的数据库，这些数据库积累越来越多。
M哥后来遇到了V哥，V哥是同行，手里面也有很多数据库，可以和M哥互补，两人一拍即合，把双方的数据库融合起来，内容变得更丰富。 而且两个人不断的进行分析维护，排除噪点数据和没有价值的数据，相互关联，刻意的去丰富一些必需的数据字段：比如QQ号和密码、比如手机号、比如身份证号。 再刻意的去交换购买补充一些极其有价值的，比如征信报告。
社工库的内容越来越丰富，而M哥和V哥两个人力量还是小，两人刻意的去联合同行，组成利益联盟，把手里面的数据都放到一个社工库，组织力量去维护去分析。
这是一个放大的效应，由于社工库的日益庞大，信息的日益完善，再加上时间的沉淀，很多数据都可以慢慢地浮出水面，可以获得相当多的信息。 目前有一些公开的社工库，信息全面性和对于用户隐私的了解以及让人震惊，但是这才是仅仅公开的社工库，对于黑客们来说其实已经是没有价值的信息。 真正地下的社工库的数据信息丰富程度要远远更大，也绝对隐匿。
利用社工库，几乎可以暴漏出一个网络用户的全部网络行为、大量的用户隐私，和一些牵扯到个人身份财产的相关的数据信息。
首先让洗库变得更加容易：由于数据量很大信息很全，很多的账号的的虚拟财产的转移就不像之前那么困难，了解到信息之多甚至都可以伪装成这个用户去进行操作了。
其次让各种诈骗变得简单：之前大多数诈骗都是光撒网模式，而社工库的完善后，可以非常有针对性对一些特定的用户进行诈骗。 利用数据技术，甚至通过木马分析一些用户QQ聊天的内容，寻找有价值的目标，和相对更信任的关系网络。 这种模式风险会更小，而且由于诈骗目标相对较大，收益更大。 在这种模式下，完成技术分析工作的一般是黑客，但是最后完成诈骗的却一般不是，黑客把按照客户要求去分析，最后把可以完成某种特定诈骗的目标连通相关信息出售（黑市称脚本）。
最后社工库也成为地下产业链的基础服务商：全面的社工库基础数据，也是精准的流量获取来源，成为流量获取分发的地下产业链的基础服务和大数据服务商。 一些特有的黑色产业目前非常依赖社工库，例如精准定位的赌博平台、一些p2p金融类型的诈骗、或者是一些商业骗术。
社工库还可以进行网络的定向攻击，有时候一些不懂行的人进入互联网，糊里糊涂的就被骗的搞的一塌糊涂，互联网并不简单，简单的是那些幼稚的主流科技媒体， 真正的中国互联网行业水很深 ，深到还没有外企可以成功的地步。
而社工库也在不断的扩大，丰富，并且继续沉寂。
*** 社工库的发展：未来趋势
从2013年以后，国内互联网黑市上的数据交易产生了严重的分层：一些大的数据盗窃团伙早已经完成早期的数据积累构建非常完善的社工库，对于一般的数据定制需求都不会再接，会专注于更深度变现更强的金融诈骗；而一些小的数据盗窃团伙还在不断的相互交易、交换数据、而且相对高调的浮出水面，其实危害反而没有那么大。
而且出于用户交互方面的考虑，目前越来越多的移动终端支付或者金融产品的安全策略略浅，再加上更丰富的网络电商活动，导致沉寂在黑产中的数据危害也越来越大。 这可能也会是更多的互联网产品的设计时需要考虑的问题所在。
而真正沉浸起来的社工库，一方面已经成为传说，另外还在构建着自己未来的目标，这些才是真正危害，也是对于我们最大的威胁。 我们TOMsInsight分析到此很矛盾：在这个主流互联网都在炒作概念玩击鼓传花的骗术，而地下互联网都在积累的年代，也许我们真的应该沉下心去仔细的去研究去分析去洞察，而不是人云亦云。
“暴漏出来的社工库都是小孩玩的，真正有价值的社工库谁也不会暴漏，都在沉寂”， M哥对我们TOMsInsight的调研员说到“有时候真的看不懂现在主流的互联网，拿几百万投资就嘚瑟的不得了，其实就是不入流的卖艺打赏呗，小孩过家家。我们这行很多人都能一天赚出来这个投资数的现金来，反而继续去沉寂，沉下心钻研，为了未来更大的打算。” M哥的话有些绝对了，但是在某种程度上也值得我们反思。
*** 给我们的启示
江湖的故事会继续，传说也会继续。 有些人可以选择视而不见，有些人也会选择去逃避。 但是冬天始终都会到来，冷暖自知。 我们不能要求每一个互联网人都踏实下来，毕竟一些浮躁的跟风卖艺求打赏也会是很多人的生存之道，但是我们应该知道，江湖并不是由他们构成，那些传说，也都和每一个故事一样的真正的存在我们的身边。
当一个行业的地下产业比主流产业更踏实，看的更长远，也更注重积累的时候，也许很值的我们所有的从业人员反思。 毕竟，传说应该属于真正的英雄！


