showmacros:
	echo HOME is $(HOME) # defined as an environment variable
	echo COMPILE.f is $(COMPILE.f) #defined as a makefile default
	echo HERBERT is $(HERBERT) # defined locally in the makefile

HERBERT=Herbivore
